export const LANGUAGE_WORDS = [
    'Language',
    'لغة',
    'Taal',
    'Langue',
    'Sprache',
    'भाषा',
    'Bahasa',
    'Lingua',
    '言語',
    '언어',
    '语言',
    '語言',
    'Język',
    'Idioma',
    'Язык',
    'ภาษา',
    'Dil',
    'Мова',
    'Ngôn ngữ',
];

export const LANGUAGE_WORD_BY_CODE: Record<string, string> = {
    en: 'Language',
    ar: 'لغة',
    nl: 'Taal',
    fr: 'Langue',
    de: 'Sprache',
    hi: 'भाषा',
    id: 'Bahasa',
    it: 'Lingua',
    ja: '言語',
    ko: '언어',
    'zh-CN': '语言',
    'zh-TW': '語言',
    pl: 'Język',
    es: 'Idioma',
    'pt-BR': 'Idioma',
    ru: 'Язык',
    th: 'ภาษา',
    tr: 'Dil',
    uk: 'Мова',
    vi: 'Ngôn ngữ',
};
