// publisher-source-names: which source names belong to which publisher, as far
// as THIS device knows. The more/fewer control writes one preference row per
// name (see publication-pref-level.ts), so an entry point that knows only one
// name (a card, "Fewer from") needs the rest from somewhere without a network
// round trip.
//
// Two local sources, in order:
//  1. Memory, filled by every response that lists a publisher's full source
//     set: the publication profile (`sourceNames`) and the Sources publisher
//     list (`newsPublishers.publicationSources`). NOT `searchPublishers`: its
//     `matchingSources` is the filtered subset that matched the query.
//  2. The subscriptions table, whose `source_names_json` holds a subscribed
//     publisher's full source set (normalized).
//
// A name that belongs to more than one known publisher is AMBIGUOUS and never
// expands: the caller writes the name it was given and nothing else. Writing
// another publisher's names would change that publisher's news.
//
// Memory only by design: this is public catalogue data, regenerated by the
// next profile or Sources load, and it holds nothing about the reader.
//
// The memory half is pure. The subscriptions half is required lazily, so a
// module that only records names (source-service, the profile service) never
// pulls the database in.

import { normalizePrefName, publisherPrefNames } from './publication-pref-level';

const namesByPublisher = new Map<string, string[]>();
const publishersByName = new Map<string, Set<string>>();

/** Record a publisher's FULL source-name set (replacing what was known). */
export function rememberPublisherSourceNames(
  publisherId: string,
  names: readonly (string | null | undefined)[],
): void {
  if (!publisherId) return;
  const next = publisherPrefNames(names);
  const previous = namesByPublisher.get(publisherId);
  if (previous) {
    for (const n of previous) publishersByName.get(normalizePrefName(n))?.delete(publisherId);
  }
  if (next.length === 0) {
    namesByPublisher.delete(publisherId);
    return;
  }
  namesByPublisher.set(publisherId, next);
  for (const n of next) {
    const key = normalizePrefName(n);
    let owners = publishersByName.get(key);
    if (!owners) {
      owners = new Set();
      publishersByName.set(key, owners);
    }
    owners.add(publisherId);
  }
}

/** The recorded source names of a publisher, or null when none are known. */
export function knownSourceNamesForPublisher(publisherId: string): string[] | null {
  return namesByPublisher.get(publisherId) ?? null;
}

/**
 * The other names of the ONE publisher that owns `name`, from memory.
 * Null when no publisher is known for it, or when more than one is.
 */
export function knownSourceNamesForName(name: string): string[] | null {
  const owners = publishersByName.get(normalizePrefName(name));
  if (!owners || owners.size !== 1) return null;
  const [publisherId] = Array.from(owners);
  return namesByPublisher.get(publisherId) ?? null;
}

/** What an entry point knows about the publication whose preference it sets. */
export interface PublicationNameHints {
  /** The publisher id, when the entry point has it. */
  readonly publisherId?: string | null;
  /** The name the entry point shows (a source name on cards, the publisher
   *  name on Sources rows). */
  readonly rawName?: string | null;
  /** The publisher's own name, when known. */
  readonly publisherName?: string | null;
  /** The publisher's full source set, when the caller already has it. */
  readonly sourceNames?: readonly string[] | null;
}

/**
 * Every name to read and write a publication's more/fewer under, using only
 * what is on the device: the caller's hints, memory, then subscriptions.
 * Never touches the network. Always includes the hints themselves, so an
 * unknown publication still gets its raw name.
 */
export async function resolvePublicationPrefNames(hints: PublicationNameHints): Promise<string[]> {
  const fromMemory =
    (hints.publisherId ? knownSourceNamesForPublisher(hints.publisherId) : null) ??
    (hints.rawName ? knownSourceNamesForName(hints.rawName) : null) ??
    (hints.publisherName ? knownSourceNamesForName(hints.publisherName) : null);
  const names = publisherPrefNames(hints.sourceNames ?? [], fromMemory ?? [], hints.publisherName, hints.rawName);
  if (hints.sourceNames?.length || fromMemory) return names;

  // Nothing in memory: a subscribed publisher still knows its sources.
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const subs = require('./user-publication-subscription-service') as typeof import('./user-publication-subscription-service');
    const active = await subs.getActive();
    const keys = new Set(names.map(normalizePrefName));
    const matches = active.filter(
      (s) =>
        (hints.publisherId && s.publisherId === hints.publisherId) ||
        keys.has(normalizePrefName(s.publisherName ?? '')) ||
        subs.parseSourceNames(s.sourceNamesJson).some((n) => keys.has(normalizePrefName(n))),
    );
    // Ambiguous across publishers: keep the caller's names only.
    if (new Set(matches.map((s) => s.publisherId)).size !== 1) return names;
    const sub = matches[0];
    return publisherPrefNames(names, sub.publisherName, subs.parseSourceNames(sub.sourceNamesJson));
  } catch {
    return names;
  }
}

/** Test seam. */
export function __clearPublisherSourceNames(): void {
  namesByPublisher.clear();
  publishersByName.clear();
}
